import type { Metadata } from 'next';
import { Reveal } from '@/components/Reveal';

export const metadata: Metadata = {
  title: 'Compare - openvidstudio',
  description:
    'How openvidstudio differs from a hosted AI-storyboard tool, plus honest notes on the two other tools from the same author.',
};

type Sibling = {
  name: string;
  tagline: string;
  problem: string;
  difference: string;
  repo: string;
};

// Real differentiation, pulled from each repo's own README "Why" section
// (personal-repos/Components, personal-repos/oss-launch), not invented.
const siblings: Sibling[] = [
  {
    name: 'Components',
    tagline: 'Showpiece UI for AI coding agents',
    problem:
      "Anthropic's frontend-design skill makes an agent design well. It does not hand you a " +
      'scroll-driven 3D MacBook or a WebGL globe: that motion is slow and bug-prone to ' +
      'hand-write, and copy-pasting from a docs site goes stale and skips attribution.',
    difference:
      'Components is a sourcing skill. It answers one question, which proven showpiece fits ' +
      'and how do you make it on-brand, by pulling the real, maintained component live at ' +
      'build time from Aceternity, Magic UI, Cult UI, ReactBits, and 21st.dev, then handing ' +
      'final polish to a quality skill. It curates pointers, not stale copies, so the code ' +
      'stays current and the upstream license travels with it.',
    repo: 'https://github.com/AnayDhawan/Components',
  },
  {
    name: 'oss-launch',
    tagline: 'Take a repo open source the right way',
    problem:
      'Most solo projects never get the boring-but-decisive OSS files: a real LICENSE, a ' +
      'contributing guide, a security policy, a README that pitches in one line.',
    difference:
      'oss-launch scans a repo (stack, existing files, git remote, secrets) and generates a ' +
      "tailored file collection in one pass, adapted to that repo's stack, instead of pasting " +
      'boilerplate that still says {{REPO}}. It also has a headless mode (scripts/apply.sh) ' +
      'for CI or a plain terminal with no agent loop at all; this very site\'s CONTRIBUTING.md, ' +
      'SECURITY.md, and CODE_OF_CONDUCT.md were generated by it.',
    repo: 'https://github.com/AnayDhawan/oss-launch',
  },
];

export default function ComparePage() {
  return (
    <div className="relative">
      {/* Sparse section background, task 4: low-opacity, behind the content
          only in the top block where the real differentiation argument
          lives, not tiled across the whole page. */}
      <img
        src="/brand/texture-compare.png"
        alt=""
        aria-hidden="true"
        className="pointer-events-none absolute inset-x-0 top-0 -z-10 h-[520px] w-full object-cover opacity-[0.08]"
      />

      <div className="mx-auto max-w-3xl px-6 py-16">
        <Reveal className="max-w-2xl">
          <p className="font-mono text-xs tracking-wide text-muted-foreground">COMPARE</p>
          <h1 className="mt-3 text-balance font-heading text-3xl font-semibold sm:text-4xl">
            Real UI, not a generated guess at it.
          </h1>
        </Reveal>

        <Reveal delayMs={60} className="mt-8">
          <p className="text-pretty leading-relaxed text-muted-foreground">
            There are hosted, MCP-callable pipelines that go storyboard to AI-generated
            visuals plus voiceover plus music plus captions in one pass. Those are genuinely
            fast for a rough pacing draft to react to, and openvidstudio does not try to
            replace that use case.
          </p>
          <p className="mt-4 text-pretty leading-relaxed text-muted-foreground">
            But that model, AI-generated visuals standing in for the product, is the opposite
            of why openvidstudio exists. openvidstudio builds a cinematic camera that moves
            over your product&apos;s real, DOM-rendered UI, composited from real
            Playwright-captured screenshots and screen recordings of the actual running app.
            Every piece of product text a viewer can read came from the real product. Where
            the real UI genuinely can&apos;t produce a shot, an optional Higgsfield tier
            covers exactly that gap, atmosphere and b-roll only, and it never carries
            on-screen product text or real UI.
          </p>
        </Reveal>

        <Reveal delayMs={100} className="mt-12 grid gap-4 sm:grid-cols-2">
          <div className="rounded-2xl border border-primary/25 bg-card p-6">
            <p className="font-mono text-xs tracking-wide text-primary">openvidstudio</p>
            <ul className="mt-4 flex flex-col gap-2 text-sm text-foreground/90">
              <li>Real, captured UI on screen</li>
              <li>No account, no key, free by default</li>
              <li>Runs through MCP tools your agent already has</li>
              <li>AI b-roll (optional) never carries product text</li>
            </ul>
          </div>
          <div className="rounded-2xl border border-dashed border-border bg-transparent p-6">
            <p className="font-mono text-xs tracking-wide text-muted-foreground">
              Generic AI video tool
            </p>
            <ul className="mt-4 flex flex-col gap-2 text-sm text-muted-foreground">
              <li>Model-generated guess at your UI</li>
              <li>Hosted, usually paid</li>
              <li>Its own separate app or dashboard</li>
              <li>Every frame is synthetic, including the product itself</li>
            </ul>
          </div>
        </Reveal>

        <Reveal delayMs={140} className="mt-16 border-t border-border pt-12">
          <p className="font-mono text-xs tracking-wide text-muted-foreground">
            SAME AUTHOR, SAME PATTERN
          </p>
          <h2 className="mt-3 text-balance font-heading text-2xl font-semibold">
            Two other tools, honestly compared to their own generic alternative.
          </h2>
          <p className="mt-4 max-w-2xl text-pretty text-sm text-muted-foreground">
            openvidstudio is one piece of a small set of open-source agent tooling from the
            same author. Each one exists because the obvious generic approach has a real gap;
            here is what each actually does and how it differs, not a generic pitch.
          </p>

          <div className="mt-8 flex flex-col gap-6">
            {siblings.map((sibling) => (
              <div key={sibling.name} className="rounded-2xl border border-border bg-card p-6">
                <div className="flex flex-wrap items-baseline justify-between gap-2">
                  <h3 className="font-heading text-lg font-semibold">{sibling.name}</h3>
                  <a
                    href={sibling.repo}
                    className="font-mono text-xs text-primary underline underline-offset-4"
                  >
                    {sibling.repo.replace('https://', '')}
                  </a>
                </div>
                <p className="mt-1 text-sm text-muted-foreground">{sibling.tagline}</p>
                <p className="mt-4 text-pretty text-sm leading-relaxed text-muted-foreground">
                  {sibling.problem}
                </p>
                <p className="mt-3 text-pretty text-sm leading-relaxed text-foreground/90">
                  {sibling.difference}
                </p>
              </div>
            ))}
          </div>
        </Reveal>
      </div>
    </div>
  );
}
