// SFX sequencer. All sounds live in public/sfx/ (generated by scripts/gen-sfx.sh).
// Components emit sounds by rendering these helpers at computed frames, audio stays
// perfectly in sync with visuals because both derive from the same frame math.

import React from "react";
import { Audio, Sequence, staticFile } from "remotion";
import { jitter } from "./motion";

const KEYS = ["key_a.wav", "key_b.wav", "key_c.wav"];

export const KeySound: React.FC<{ at: number; seed?: number; volume?: number }> = ({
  at,
  seed = 0,
  volume = 0.16,
}) => (
  <Sequence from={at} durationInFrames={6}>
    <Audio
      src={staticFile(`sfx/${KEYS[Math.floor(jitter(at, seed) * KEYS.length)]}`)}
      volume={volume}
    />
  </Sequence>
);

/** One KeySound per typed character. charFrames = absolute frame each char appears. */
export const TypingSfx: React.FC<{ charFrames: number[]; volume?: number }> = ({
  charFrames,
  volume = 0.16,
}) => (
  <>
    {charFrames.map((f, i) => (
      <KeySound key={i} at={f} seed={i} volume={volume} />
    ))}
  </>
);

export const Click: React.FC<{ at: number; volume?: number }> = ({
  at,
  volume = 0.4,
}) => (
  <Sequence from={at} durationInFrames={8}>
    <Audio src={staticFile("sfx/click.wav")} volume={volume} />
  </Sequence>
);

export const Whoosh: React.FC<{ at: number; volume?: number }> = ({
  at,
  volume = 0.35,
}) => (
  <Sequence from={at} durationInFrames={20}>
    <Audio src={staticFile("sfx/whoosh.wav")} volume={volume} />
  </Sequence>
);

export const Blip: React.FC<{ at: number; volume?: number }> = ({
  at,
  volume = 0.3,
}) => (
  <Sequence from={at} durationInFrames={8}>
    <Audio src={staticFile("sfx/blip.wav")} volume={volume} />
  </Sequence>
);

export const SuccessChime: React.FC<{ at: number; volume?: number }> = ({
  at,
  volume = 0.35,
}) => (
  <Sequence from={at} durationInFrames={20}>
    <Audio src={staticFile("sfx/success.wav")} volume={volume} />
  </Sequence>
);

/** Struck bell, for a completion moment that wants more weight than a chime. */
export const Bell: React.FC<{ at: number; volume?: number }> = ({
  at,
  volume = 0.3,
}) => (
  <Sequence from={at} durationInFrames={48}>
    <Audio src={staticFile("sfx/bell.wav")} volume={volume} />
  </Sequence>
);

/** Enter key. Deeper and heavier than a letter key, for the end of a typed command. */
export const EnterKey: React.FC<{ at: number; volume?: number }> = ({
  at,
  volume = 0.2,
}) => (
  <Sequence from={at} durationInFrames={8}>
    <Audio src={staticFile("sfx/key_enter.wav")} volume={volume} />
  </Sequence>
);

/**
 * Ambient bed under the whole composition.
 *
 * Synthesized by scripts/gen-sfx.sh rather than licensed, so a rendered video
 * carries no third-party audio rights. The source is 60s; `durationInFrames` loops
 * it to cover the composition.
 */
export const MusicBed: React.FC<{ durationInFrames: number; volume?: number }> = ({
  durationInFrames,
  volume = 0.16,
}) => (
  <Sequence from={0} durationInFrames={durationInFrames}>
    <Audio src={staticFile("sfx/music-bed.wav")} volume={volume} loop />
  </Sequence>
);
