// SFX sequencer. All sounds live in public/sfx/ (generated by scripts/gen-sfx.sh, except
// typing-effect.mp3, a copyright-free recording committed as-is).
// Components emit sounds by rendering these helpers at computed frames, audio stays
// perfectly in sync with visuals because both derive from the same frame math.

import React from "react";
import { Audio, Sequence, interpolate, staticFile } from "remotion";

// typing-effect.mp3 is one continuous 8.1s recording of typing: a quiet lead-in, then steady keys.
const TYPING_FILE = "sfx/typing-effect.mp3";
const TYPING_SKIP = 12; // frames of lead-in to skip
const TYPING_PASS = 8 * 30 - TYPING_SKIP - 8; // frames of steady typing per pass through the file
const TYPING_GAP = 24; // a pause longer than this many frames starts a new typing run
const TYPING_FADE = 5;

/**
 * Plays the typing recording under typed text. charFrames = absolute frame each char appears.
 * Characters closer together than TYPING_GAP frames form one run; the recording plays across the
 * run (looping in passes when the run is longer than the file), fading in and out so it never
 * clicks. One continuous recording, not one sample per key, so typing does not sound like a metronome.
 */
export const TypingSfx: React.FC<{ charFrames: number[]; volume?: number }> = ({
  charFrames,
  volume = 1,
}) => {
  const frames = [...charFrames].sort((x, y) => x - y);
  const runs: [number, number][] = [];
  for (const f of frames) {
    const last = runs[runs.length - 1];
    if (last && f - last[1] <= TYPING_GAP) last[1] = f;
    else runs.push([f, f]);
  }
  return (
    <>
      {runs.flatMap(([first, lastFrame], runIdx) => {
        const start = first - 1;
        const total = lastFrame - first + 6;
        const passes = Math.ceil(total / TYPING_PASS);
        return Array.from({ length: passes }, (_, p) => {
          const len = Math.min(TYPING_PASS, total - p * TYPING_PASS);
          return (
            <Sequence key={runIdx + "-" + p} from={start + p * TYPING_PASS} durationInFrames={len}>
              <Audio
                src={staticFile(TYPING_FILE)}
                startFrom={TYPING_SKIP}
                volume={(f) =>
                  volume *
                  interpolate(f, [0, TYPING_FADE, len - TYPING_FADE, len], [0, 1, 1, 0], {
                    extrapolateLeft: "clamp",
                    extrapolateRight: "clamp",
                  })
                }
              />
            </Sequence>
          );
        });
      })}
    </>
  );
};

export const Click: React.FC<{ at: number; volume?: number }> = ({
  at,
  volume = 0.4,
}) => (
  <Sequence from={at} durationInFrames={8}>
    <Audio src={staticFile("sfx/click.wav")} volume={volume} />
  </Sequence>
);

export const Whoosh: React.FC<{ at: number; volume?: number }> = ({
  at,
  volume = 0.35,
}) => (
  <Sequence from={at} durationInFrames={20}>
    <Audio src={staticFile("sfx/whoosh.wav")} volume={volume} />
  </Sequence>
);

export const Blip: React.FC<{ at: number; volume?: number }> = ({
  at,
  volume = 0.3,
}) => (
  <Sequence from={at} durationInFrames={8}>
    <Audio src={staticFile("sfx/blip.wav")} volume={volume} />
  </Sequence>
);

export const SuccessChime: React.FC<{ at: number; volume?: number }> = ({
  at,
  volume = 0.35,
}) => (
  <Sequence from={at} durationInFrames={20}>
    <Audio src={staticFile("sfx/success.wav")} volume={volume} />
  </Sequence>
);

/** Struck bell, for a completion moment that wants more weight than a chime. */
export const Bell: React.FC<{ at: number; volume?: number }> = ({
  at,
  volume = 0.3,
}) => (
  <Sequence from={at} durationInFrames={48}>
    <Audio src={staticFile("sfx/bell.wav")} volume={volume} />
  </Sequence>
);

/**
 * Ambient bed under the whole composition.
 *
 * Synthesized by scripts/gen-sfx.sh rather than licensed, so a rendered video
 * carries no third-party audio rights. The source is 60s; `durationInFrames` loops
 * it to cover the composition.
 */
export const MusicBed: React.FC<{ durationInFrames: number; volume?: number }> = ({
  durationInFrames,
  volume = 0.16,
}) => (
  <Sequence from={0} durationInFrames={durationInFrames}>
    <Audio src={staticFile("sfx/music-bed.mp3")} volume={volume} loop />
  </Sequence>
);
