import * as fs from "node:fs";
import * as path from "node:path";
import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { resolveProjectRoot, sanitizeSegment, pascalCase } from "../util";
import { runTool } from "./mcp";

export type SceneKind = "real-screenshot" | "real-recording" | "dom-demo" | "higgsfield-clip";

export interface ScaffoldSceneInput {
  projectRoot?: string;
  videoName: string;
  beatId: string;
  kind: SceneKind;
  overwrite?: boolean;
}

export interface ScaffoldSceneResult {
  written: true;
  path: string;
  componentName: string;
}

const CAMERA_BLOCK = `      camera={[
        { frame: 0, x: 960, y: 540, scale: 1.2 },
        { frame: 240, x: 960, y: 540, scale: 1.35 },
      ]}`;

const CAPTURE_FRAME_CONSTANTS = `// TODO: measure the real capture and set these per CAPTURE.md's frame-sizing formula:
//   FRAME_W = <capture width>
//   FRAME_H = <capture height> + 56   // BrowserFrame's chrome bar
//   LEFT = (1920 - FRAME_W) / 2
//   TOP = (1080 - FRAME_H) / 2
const FRAME_W = 1600;
const FRAME_H = 1056;
const LEFT = (1920 - FRAME_W) / 2;
const TOP = (1080 - FRAME_H) / 2;`;

/**
 * Asset path conventions a scaffolded scene references (Task 4/5 must match these
 * exactly):
 *   - real-screenshot:                 public/images/<beatId>.png
 *   - real-recording / higgsfield-clip: public/video/<beatId>.mp4
 */
function sceneSource(kind: SceneKind, beatId: string, componentName: string): string {
  if (kind === "real-screenshot") {
    return `// Scene stub for beat "${beatId}" (kind: real-screenshot). Generated by scaffold_scene.
// Capture per CAPTURE.md, then fill in the camera keyframes and overlay captions.

import React from "react";
import { Img, staticFile } from "remotion";
import { CinematicScene, Layer, BrowserFrame } from "@openvidstudio/core";

${CAPTURE_FRAME_CONSTANTS}

export const ${componentName}: React.FC = () => {
  return (
    <CinematicScene
${CAMERA_BLOCK}
      overlay={<></>}
    >
      <Layer depth={0}>
        <div style={{ position: "absolute", left: LEFT, top: TOP }}>
          <BrowserFrame url="TODO: set the captured page's URL" width={FRAME_W} height={FRAME_H}>
            <Img
              src={staticFile("images/${beatId}.png")}
              style={{ width: "100%", height: "100%", objectFit: "cover" }}
            />
          </BrowserFrame>
        </div>
      </Layer>
    </CinematicScene>
  );
};
`;
  }

  if (kind === "real-recording" || kind === "higgsfield-clip") {
    const sourceNote =
      kind === "higgsfield-clip"
        ? `// Asset comes from the call_higgsfield tool (Task 5), not a screen recording -- but the\n` +
          `// composited shape is identical to a real-recording beat: an OffthreadVideo in a Layer.`
        : `// Capture per CAPTURE.md's recording section, then fill in the camera keyframes.`;
    return `// Scene stub for beat "${beatId}" (kind: ${kind}). Generated by scaffold_scene.
${sourceNote}

import React from "react";
import { OffthreadVideo, staticFile } from "remotion";
import { CinematicScene, Layer, BrowserFrame } from "@openvidstudio/core";

${CAPTURE_FRAME_CONSTANTS}

export const ${componentName}: React.FC = () => {
  return (
    <CinematicScene
${CAMERA_BLOCK}
      overlay={<></>}
    >
      <Layer depth={0}>
        <div style={{ position: "absolute", left: LEFT, top: TOP }}>
          <BrowserFrame url="TODO: set the captured page's URL" width={FRAME_W} height={FRAME_H}>
            <OffthreadVideo
              src={staticFile("video/${beatId}.mp4")}
              style={{ width: "100%", height: "100%", objectFit: "cover" }}
            />
          </BrowserFrame>
        </div>
      </Layer>
    </CinematicScene>
  );
};
`;
  }

  // dom-demo
  return `// Scene stub for beat "${beatId}" (kind: dom-demo). Generated by scaffold_scene.
// No capture step: build a hand-coded panel using @openvidstudio/core's tokens.

import React from "react";
import { CinematicScene, Layer } from "@openvidstudio/core";

export const ${componentName}: React.FC = () => {
  return (
    <CinematicScene
${CAMERA_BLOCK}
      overlay={<></>}
    >
      <Layer depth={0}>
        {/* TODO: build a hand-coded panel using @openvidstudio/core's tokens */}
        <></>
      </Layer>
    </CinematicScene>
  );
};
`;
}

export function runScaffoldScene(input: ScaffoldSceneInput): ScaffoldSceneResult {
  const videoName = sanitizeSegment(input.videoName, "videoName");
  const beatId = sanitizeSegment(input.beatId, "beatId");
  const projectRoot = resolveProjectRoot(input.projectRoot);
  const componentName = pascalCase(beatId);
  const scenesDir = path.join(projectRoot, "src", "videos", videoName, "scenes");
  const filePath = path.join(scenesDir, `${componentName}.tsx`);

  if (fs.existsSync(filePath) && !input.overwrite) {
    throw new Error(
      `${filePath} already exists. Pass overwrite: true to replace a scene the calling agent or dev has ` +
        `already started editing.`,
    );
  }

  fs.mkdirSync(scenesDir, { recursive: true });
  fs.writeFileSync(filePath, sceneSource(input.kind, beatId, componentName), "utf8");

  return { written: true, path: filePath, componentName };
}

export function registerScaffoldScene(server: McpServer): void {
  server.registerTool(
    "scaffold_scene",
    {
      title: "Scaffold a scene stub for one beat",
      description:
        "Writes src/videos/<videoName>/scenes/<BeatId>.tsx, pre-wired to CinematicScene from " +
        "@openvidstudio/core with a Layer/camera skeleton and an empty overlay prop. beatId is PascalCased " +
        "for the component/file name: split on any run of non-alphanumeric characters, capitalize each " +
        "remaining segment, join (a leading digit gets an 'S' prefix). Varies by kind: real-screenshot " +
        "(Img in a BrowserFrame, asset at public/images/<beatId>.png, with a TODO pointing at CAPTURE.md's " +
        "frame-sizing formula); real-recording and higgsfield-clip (structurally identical: OffthreadVideo " +
        "in a BrowserFrame, asset at public/video/<beatId>.mp4 -- higgsfield-clip's asset comes from the " +
        "not-yet-built call_higgsfield tool instead of a screen recording, everything else about the shape " +
        "is the same); dom-demo (bare Layer, a TODO comment, no capture boilerplate). Refuses to overwrite " +
        "an existing scene file unless overwrite: true is passed, so it never silently clobbers a scene " +
        "someone has already started editing.",
      inputSchema: {
        projectRoot: z.string().optional(),
        videoName: z.string().min(1),
        beatId: z.string().min(1),
        kind: z.enum(["real-screenshot", "real-recording", "dom-demo", "higgsfield-clip"]),
        overwrite: z.boolean().optional(),
      },
    },
    async (input) => runTool("scaffold_scene", () => runScaffoldScene(input)),
  );
}
