import { spawnSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { resolveProjectRoot, sanitizeSegment } from "../util";
import { runTool } from "./mcp";

/**
 * Sourcing sound effects that are not in the synthesized pack.
 *
 * The built-in pack is generated by ffmpeg from anoisesrc and sine, so it carries no
 * third-party rights at all. That is a real property of this project and the reason
 * the default here is "use what is already there": every sound you add from outside
 * gives that up, and CC-BY material has to be credited in the video description or you
 * are in breach of the licence.
 *
 * On Pixabay specifically. Their Terms of Service prohibit "data mining, extraction,
 * scraping and the use of programs or robots for automatic data collection", and state
 * that the API "is made for real human requests" with "systematic mass downloads" not
 * allowed. Their public API also covers images and video only; there is no documented
 * sound-effects endpoint. So a tool that downloads from Pixabay on the user's behalf
 * would have to scrape, and shipping that in an open-source package would put every
 * install in breach. What this tool does instead is prepare the search: it works out
 * which sounds are missing, hands back one Pixabay search link per gap and the exact
 * path to save each file to, and then verifies and normalizes whatever the user
 * actually downloaded. The human does the download, which is the part Pixabay's terms
 * are written around.
 *
 * Freesound is offered as the automated path because it has a real public API built
 * for programmatic access. It needs the user's own token and it records the licence
 * and attribution for every clip it fetches.
 */

/** The synthesized pack that ships with @openvidstudio/core. No rights attached. */
const BUILT_IN: Record<string, string> = {
  bell: "soft notification chime, harmonic stack",
  blip: "short UI beep",
  click: "mouse or UI click",
  key_a: "keystroke variant a",
  key_b: "keystroke variant b",
  key_c: "keystroke variant c",
  key_enter: "return key, heavier than a keystroke",
  success: "positive confirmation tone",
  whoosh: "transition sweep",
  "music-bed": "ambient background bed, detuned sines plus pink noise",
};

/**
 * Maps a plain-English request onto the built-in pack, so the tool can say "you already
 * have this" instead of sending someone to download a click sound that ships in the box.
 */
const SYNONYMS: [RegExp, string][] = [
  [/\b(click|tap|press|button)\b/i, "click"],
  [/\b(key|keystroke|typing|type|keyboard)\b/i, "key_a"],
  [/\b(enter|return|submit)\b/i, "key_enter"],
  [/\b(success|complete|done|confirm|finish)\b/i, "success"],
  [/\b(whoosh|swoosh|transition|sweep|swipe)\b/i, "whoosh"],
  [/\b(bell|chime|notification|ding|alert)\b/i, "bell"],
  [/\b(blip|beep|bloop|tick)\b/i, "blip"],
  [/\b(music|bed|ambient|background|underscore|track)\b/i, "music-bed"],
];

const AUDIO_EXT = [".mp3", ".wav", ".ogg", ".m4a", ".flac"];

export type SfxProvider = "manual" | "freesound";

export interface SoundEffectNeed {
  /** Filename stem the scene will reference, e.g. "error_buzz". */
  id: string;
  /** What the sound should be, in plain English. Drives the search query. */
  description: string;
}

export interface SoundEffectsInput {
  projectRoot?: string;
  /** What the video needs. Ask the user for these rather than guessing. */
  needs: SoundEffectNeed[];
  provider?: SfxProvider;
  /** Re-check what landed on disk and normalize it, instead of planning. */
  verify?: boolean;
  /** Freesound only. Falls back to FREESOUND_API_KEY. */
  freesoundToken?: string;
  /** Convert everything to a single format on verify. */
  normalizeTo?: "mp3" | "wav";
}

interface PlannedNeed {
  id: string;
  description: string;
  status: "already-built-in" | "needs-download" | "present";
  builtInName?: string;
  searchUrl?: string;
  savePath?: string;
  file?: string;
  durationSec?: number;
  license?: string;
  attribution?: string;
}

export interface SoundEffectsResult {
  provider: SfxProvider;
  sfxDir: string;
  needs: PlannedNeed[];
  covered: number;
  outstanding: number;
  attributionFile?: string;
  licenceNote: string;
  nextStep: string;
}

function matchBuiltIn(description: string, id: string): string | null {
  const hay = `${id} ${description}`;
  if (BUILT_IN[id]) return id;
  for (const [re, name] of SYNONYMS) if (re.test(hay)) return name;
  return null;
}

function probeDuration(file: string): number | null {
  const r = spawnSync(
    "ffprobe",
    ["-v", "error", "-show_entries", "format=duration", "-of", "default=nw=1:nk=1", file],
    { encoding: "utf8" },
  );
  const d = Number.parseFloat((r.stdout ?? "").trim());
  return Number.isFinite(d) && d > 0 ? d : null;
}

function findExisting(sfxDir: string, id: string): string | null {
  for (const ext of AUDIO_EXT) {
    const p = path.join(sfxDir, `${id}${ext}`);
    if (fs.existsSync(p)) return p;
  }
  return null;
}

/** Pixabay's own search page for this sound. The user downloads from here by hand. */
function pixabaySearchUrl(description: string): string {
  return `https://pixabay.com/sound-effects/search/${encodeURIComponent(description.trim())}/`;
}

interface FreesoundHit {
  name: string;
  username: string;
  license: string;
  previewUrl: string;
  id: number;
}

async function freesoundSearch(query: string, token: string): Promise<FreesoundHit | null> {
  const url =
    "https://freesound.org/apiv2/search/text/?" +
    new URLSearchParams({
      query,
      fields: "id,name,username,license,previews",
      page_size: "1",
      token,
    }).toString();

  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(
      `Freesound returned ${res.status}. A 401 means the token is wrong; a 429 means you are over the rate limit.`,
    );
  }
  const body = (await res.json()) as {
    results?: {
      id: number;
      name: string;
      username: string;
      license: string;
      previews?: Record<string, string>;
    }[];
  };
  const hit = body.results?.[0];
  if (!hit) return null;
  const preview = hit.previews?.["preview-hq-mp3"] ?? hit.previews?.["preview-lq-mp3"];
  if (!preview) return null;
  return {
    id: hit.id,
    name: hit.name,
    username: hit.username,
    license: hit.license,
    previewUrl: preview,
  };
}

async function download(url: string, dest: string): Promise<void> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`download failed with ${res.status} for ${url}`);
  const buf = Buffer.from(await res.arrayBuffer());
  if (buf.byteLength < 1024) throw new Error(`downloaded file is too small to be audio: ${dest}`);
  fs.writeFileSync(dest, buf);
}

/** Re-encode to one format so scenes are not guessing at extensions. */
function normalize(file: string, to: "mp3" | "wav"): string {
  const target = file.replace(/\.[^.]+$/, `.${to}`);
  if (target === file) return file;
  const args =
    to === "mp3"
      ? ["-v", "error", "-i", file, "-c:a", "libmp3lame", "-b:a", "160k", target, "-y"]
      : ["-v", "error", "-i", file, "-c:a", "pcm_s16le", "-ar", "44100", target, "-y"];
  const r = spawnSync("ffmpeg", args, { encoding: "utf8" });
  if (r.status !== 0) return file;
  fs.rmSync(file, { force: true });
  return target;
}

function writeAttribution(sfxDir: string, rows: PlannedNeed[]): string | undefined {
  const credited = rows.filter((r) => r.attribution);
  if (credited.length === 0) return undefined;
  const out = path.join(sfxDir, "ATTRIBUTION.md");
  const lines = [
    "# Sound effect attribution",
    "",
    "These clips came from outside the synthesized pack and carry licence terms.",
    "Reproduce this list in the video description. Removing it can breach the licence.",
    "",
    "| File | Source | Author | Licence |",
    "|---|---|---|---|",
    ...credited.map((r) => `| ${path.basename(r.file ?? r.id)} | ${r.attribution} | | ${r.license ?? "see source"} |`),
    "",
    "Everything else in this directory is generated by ffmpeg and carries no third-party rights.",
    "",
  ];
  fs.writeFileSync(out, lines.join("\n"), "utf8");
  return out;
}

export async function runSoundEffects(input: SoundEffectsInput): Promise<SoundEffectsResult> {
  const root = resolveProjectRoot(input.projectRoot);
  const sfxDir = path.join(root, "public", "sfx");
  fs.mkdirSync(sfxDir, { recursive: true });

  const provider: SfxProvider = input.provider ?? "manual";
  const token = input.freesoundToken ?? process.env.FREESOUND_API_KEY ?? "";
  if (provider === "freesound" && !token) {
    throw new Error(
      "Freesound needs a token. Create a free account, make an API key at " +
        "freesound.org/apiv2/apply, then pass freesoundToken or set FREESOUND_API_KEY.",
    );
  }

  const rows: PlannedNeed[] = [];

  for (const need of input.needs) {
    const id = sanitizeSegment(need.id, "sound effect id");
    const builtIn = matchBuiltIn(need.description, id);

    if (builtIn) {
      rows.push({
        id,
        description: need.description,
        status: "already-built-in",
        builtInName: builtIn,
        file: `sfx/${builtIn}${builtIn === "music-bed" ? ".mp3" : ".wav"}`,
      });
      continue;
    }

    const existing = findExisting(sfxDir, id);
    if (existing) {
      const file = input.verify && input.normalizeTo ? normalize(existing, input.normalizeTo) : existing;
      rows.push({
        id,
        description: need.description,
        status: "present",
        file: path.relative(root, file).replace(/\\/g, "/"),
        durationSec: probeDuration(file) ?? undefined,
      });
      continue;
    }

    if (provider === "freesound" && !input.verify) {
      const hit = await freesoundSearch(need.description, token);
      if (hit) {
        const dest = path.join(sfxDir, `${id}.mp3`);
        await download(hit.previewUrl, dest);
        rows.push({
          id,
          description: need.description,
          status: "present",
          file: path.relative(root, dest).replace(/\\/g, "/"),
          durationSec: probeDuration(dest) ?? undefined,
          license: hit.license,
          attribution: `freesound.org/s/${hit.id} by ${hit.username}`,
        });
        continue;
      }
    }

    rows.push({
      id,
      description: need.description,
      status: "needs-download",
      searchUrl: pixabaySearchUrl(need.description),
      savePath: path.join(sfxDir, `${id}.mp3`),
    });
  }

  const outstanding = rows.filter((r) => r.status === "needs-download").length;
  const covered = rows.length - outstanding;
  const attributionFile = writeAttribution(sfxDir, rows);

  const nextStep =
    outstanding === 0
      ? "Every sound is accounted for. Reference them from scenes as sfx/<id>."
      : `Open each searchUrl, pick a sound, and save it to the matching savePath. ` +
        `Then call this tool again with verify: true to confirm each file is real audio and normalize it.`;

  return {
    provider,
    sfxDir,
    needs: rows,
    covered,
    outstanding,
    attributionFile,
    licenceNote:
      "The built-in pack is synthesized by ffmpeg and carries no third-party rights. " +
      "Anything downloaded does carry terms: Pixabay content is covered by their Content Licence, " +
      "and Freesound clips are per-clip CC and often require credit. Whatever lands in ATTRIBUTION.md " +
      "belongs in the video description.",
    nextStep,
  };
}

export function registerSoundEffects(server: McpServer): void {
  server.registerTool(
    "plan_sound_effects",
    {
      title: "Work out which sound effects are needed and where to get them",
      description:
        "Ask the user what sounds the video needs, then call this with one entry per sound. It first " +
        "checks the synthesized pack that ships with the project, which already covers clicks, " +
        "keystrokes, a bell, a blip, a success tone, a whoosh and a music bed, so people are not sent " +
        "off to download a click sound that is already in the box. For anything genuinely missing it " +
        "returns a Pixabay search link and the exact path to save the file to. It does not download " +
        "from Pixabay: their terms prohibit automated collection and state the API is for real human " +
        "requests, and they have no public sound-effects endpoint, so the user does that step. Set " +
        "provider to 'freesound' to fetch automatically instead, which needs the user's own API token " +
        "and records licence and attribution per clip. Call again with verify true once files are in " +
        "place to confirm each one is real audio and normalize the formats. Note that the built-in pack " +
        "carries no third-party rights at all, and every downloaded sound gives that up, so prefer the " +
        "built-ins when they fit.",
      inputSchema: {
        projectRoot: z.string().optional(),
        needs: z
          .array(
            z.object({
              id: z.string().min(1),
              description: z.string().min(1),
            }),
          )
          .min(1),
        provider: z.enum(["manual", "freesound"]).optional(),
        verify: z.boolean().optional(),
        freesoundToken: z.string().optional(),
        normalizeTo: z.enum(["mp3", "wav"]).optional(),
      },
    },
    async (input) => runTool("plan_sound_effects", () => runSoundEffects(input)),
  );
}
