import * as fs from "node:fs";
import * as path from "node:path";
import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { loadConfig } from "../config";
import { resolveProjectRoot, sanitizeSegment, pascalCase } from "../util";
import { runTool } from "./mcp";

export interface StitchCompositionInput {
  projectRoot?: string;
  videoName: string;
}

export interface StitchCompositionResult {
  written: true;
  compositionId: string;
  demoPath: string;
  rootPath: string;
  durationInFrames: number;
  voBeatsFound: string[];
  musicBedFound: boolean;
}

interface RegistryEntry {
  id: string;
  videoName: string;
  componentName: string;
  importPath: string;
  durationInFrames: number;
  fps: number;
  width: number;
  height: number;
}

interface BeatLike {
  id: string;
  start: number;
  duration: number;
}

/**
 * Registry of every video this project has stitched, one entry per stitch_composition
 * call, at src/videos/.registry.json. Root.tsx is fully regenerated from this file on
 * every call rather than round-tripped via regex/JSX parsing, which is what makes it
 * safe to never clobber a composition a prior call registered for a different video:
 * the registry (not Root.tsx itself) is the actual source of truth. Deliberately not
 * part of openvidstudio.config.json: that shape is pinned for Task 5 to depend on,
 * this is internal bookkeeping local to this one tool.
 */
function registryPath(projectRoot: string): string {
  return path.join(projectRoot, "src", "videos", ".registry.json");
}

function readRegistry(projectRoot: string): RegistryEntry[] {
  const p = registryPath(projectRoot);
  if (!fs.existsSync(p)) return [];
  return JSON.parse(fs.readFileSync(p, "utf8")) as RegistryEntry[];
}

function writeRegistry(projectRoot: string, entries: RegistryEntry[]): void {
  const p = registryPath(projectRoot);
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, JSON.stringify(entries, null, 2) + "\n", "utf8");
}

function renderRootTsx(entries: RegistryEntry[]): string {
  const imports = entries.map((e) => `import { ${e.componentName} } from "${e.importPath}";`).join("\n");
  const comps = entries
    .map(
      (e) =>
        `      <Composition\n        id="${e.id}"\n        component={${e.componentName}}\n` +
        `        durationInFrames={${e.durationInFrames}}\n        fps={${e.fps}}\n` +
        `        width={${e.width}}\n        height={${e.height}}\n      />`,
    )
    .join("\n");
  return `// AUTO-GENERATED by openvidstudio's stitch_composition MCP tool.
// Source of truth is src/videos/.registry.json -- hand edits to this file are lost the
// next time stitch_composition runs for ANY video in this project, not just the one you
// edited. Add a video by calling stitch_composition, not by editing this directly.

import React from "react";
import { Composition } from "remotion";
${imports}

export const RemotionRoot: React.FC = () => {
  return (
    <>
${comps}
    </>
  );
};
`;
}

function renderDemoTsx(opts: {
  componentName: string;
  beats: BeatLike[];
  voMap: Record<string, string>;
  musicBedFound: boolean;
}): string {
  const { componentName, beats, voMap, musicBedFound } = opts;
  const sceneImports = beats
    .map((b) => `import { ${pascalCase(b.id)} } from "./scenes/${pascalCase(b.id)}";`)
    .join("\n");
  const sceneMapLines = beats.map((b) => `  ${JSON.stringify(b.id)}: ${pascalCase(b.id)},`).join("\n");
  const voLines = Object.entries(voMap)
    .map(([id, rel]) => `  ${JSON.stringify(id)}: ${JSON.stringify(rel)},`)
    .join("\n");

  const musicBedBlock = musicBedFound
    ? `      <Sequence from={0} durationInFrames={DURATION_IN_FRAMES} layout="none">
        <Audio src={staticFile("audio/music-bed.mp3")} volume={0.18} loop />
      </Sequence>
`
    : "";

  return `// AUTO-GENERATED by openvidstudio's stitch_composition MCP tool from beats.json.
// Re-run stitch_composition after editing beats.json rather than hand-editing this file;
// it will be overwritten.

import React from "react";
import { AbsoluteFill, Audio, Sequence, Series, staticFile } from "remotion";
import beats from "./beats.json";
${sceneImports}

const SCENES: Record<string, React.FC> = {
${sceneMapLines}
};

const VO_FILES: Record<string, string> = {
${voLines}
};

const last = beats.beats[beats.beats.length - 1];
export const DURATION_IN_FRAMES = last.start + last.duration;

export const ${componentName}: React.FC = () => {
  return (
    <AbsoluteFill>
      <Series>
        {beats.beats.map((b) => {
          const Scene = SCENES[b.id];
          return (
            <Series.Sequence key={b.id} durationInFrames={b.duration} name={b.id}>
              <Scene />
            </Series.Sequence>
          );
        })}
      </Series>
      {beats.beats
        .filter((b) => VO_FILES[b.id])
        .map((b) => (
          <Sequence key={\`vo-\${b.id}\`} from={b.start} durationInFrames={b.duration} layout="none">
            <Audio src={staticFile(VO_FILES[b.id])} volume={0.9} />
          </Sequence>
        ))}
${musicBedBlock}    </AbsoluteFill>
  );
};
`;
}

/**
 * Reads src/videos/<videoName>/beats.json and writes the composition + updates
 * src/Root.tsx (via the registry above). VO convention: public/audio/vo/<beatId>.mp3,
 * included only if the file actually exists on disk (mirrors PepirosDemo.tsx, where
 * the cta beat has no VO entry because none was recorded). Music bed convention:
 * public/audio/music-bed.mp3, included as a full-duration looping layer only if it
 * exists.
 */
export function runStitchComposition(input: StitchCompositionInput): StitchCompositionResult {
  const videoName = sanitizeSegment(input.videoName, "videoName");
  const projectRoot = resolveProjectRoot(input.projectRoot);
  const videoDir = path.join(projectRoot, "src", "videos", videoName);
  const beatsPath = path.join(videoDir, "beats.json");

  if (!fs.existsSync(beatsPath)) {
    throw new Error(`${beatsPath} does not exist. Call write_beats_file for "${videoName}" first.`);
  }
  const beatsData = JSON.parse(fs.readFileSync(beatsPath, "utf8")) as {
    fps?: number;
    beats?: BeatLike[];
  };
  const beats = beatsData.beats;
  if (!Array.isArray(beats) || beats.length === 0) {
    throw new Error(`${beatsPath} has no beats.`);
  }

  const config = loadConfig(projectRoot);
  const fps = beatsData.fps ?? config.videoConfig.fps;
  const last = beats[beats.length - 1];
  const durationInFrames = last.start + last.duration;

  const voMap: Record<string, string> = {};
  for (const b of beats) {
    const voFile = path.join(projectRoot, "public", "audio", "vo", `${b.id}.mp3`);
    if (fs.existsSync(voFile)) {
      voMap[b.id] = `audio/vo/${b.id}.mp3`;
    }
  }
  const musicBedFound = fs.existsSync(path.join(projectRoot, "public", "audio", "music-bed.mp3"));

  const componentName = `${pascalCase(videoName)}Demo`;
  const demoTsx = renderDemoTsx({ componentName, beats, voMap, musicBedFound });
  const demoPath = path.join(videoDir, `${componentName}.tsx`);
  fs.writeFileSync(demoPath, demoTsx, "utf8");

  const entries = readRegistry(projectRoot).filter((e) => e.videoName !== videoName);
  entries.push({
    id: componentName,
    videoName,
    componentName,
    importPath: `./videos/${videoName}/${componentName}`,
    durationInFrames,
    fps,
    width: config.videoConfig.width,
    height: config.videoConfig.height,
  });
  writeRegistry(projectRoot, entries);

  const rootPath = path.join(projectRoot, "src", "Root.tsx");
  fs.writeFileSync(rootPath, renderRootTsx(entries), "utf8");

  return {
    written: true,
    compositionId: componentName,
    demoPath,
    rootPath,
    durationInFrames,
    voBeatsFound: Object.keys(voMap),
    musicBedFound,
  };
}

export function registerStitchComposition(server: McpServer): void {
  server.registerTool(
    "stitch_composition",
    {
      title: "Stitch a video's beats into a composition",
      description:
        "Reads src/videos/<videoName>/beats.json and writes src/videos/<videoName>/<PascalName>Demo.tsx: a " +
        "SCENES map from beat id to its scaffold_scene component (imported from ./scenes/<BeatId>, the same " +
        "PascalCase convention scaffold_scene uses -- beats without a scaffolded scene file will fail to " +
        "type-check, scaffold every beat first), a <Series> of <Series.Sequence> per beat, a VO Audio layer " +
        "per beat only where public/audio/vo/<beatId>.mp3 actually exists on disk, and a looping " +
        "full-duration music bed layer if public/audio/music-bed.mp3 exists. Also (re)registers the " +
        "composition in src/Root.tsx (via an internal src/videos/.registry.json this tool owns), without " +
        "clobbering compositions a prior stitch_composition call registered for a different video in the " +
        "same project.",
      inputSchema: {
        projectRoot: z.string().optional(),
        videoName: z.string().min(1),
      },
    },
    async (input) => runTool("stitch_composition", () => runStitchComposition(input)),
  );
}
