import * as fs from "node:fs";
import * as path from "node:path";
import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { loadConfig } from "../config";
import { resolveProjectRoot, sanitizeSegment, pascalCase } from "../util";
import { runTool } from "./mcp";

export interface StitchCompositionInput {
  projectRoot?: string;
  videoName: string;
  /**
   * Fail instead of silently shipping a partly-silent video. A missing VO file has
   * always been survivable-by-design, but "survivable" quietly became "invisible":
   * the Audio layer is skipped with no error and the render succeeds, so the first
   * time anyone notices is on playback. Presets that declare narration mandatory
   * (2min-demo, 5min-demo) should set this.
   */
  requireNarration?: boolean;
  /**
   * Emit one composition per language, reading each language's narration from its own
   * directory. Defaults to the base language alone, which is every existing project.
   */
  languages?: string[];
  /** The language public/audio/vo/<beatId>.mp3 is in. Defaults to en. */
  baseLanguage?: string;
}

export interface LanguageComposition {
  language: string;
  compositionId: string;
  voBeatsFound: string[];
  voBeatsMissing: string[];
}

export interface StitchCompositionResult {
  written: true;
  compositionId: string;
  demoPath: string;
  rootPath: string;
  durationInFrames: number;
  voBeatsFound: string[];
  /** Beats that will render silent. Previously knowable only by diffing two lists by hand. */
  voBeatsMissing: string[];
  musicBedFound: boolean;
  /** Plain-language notices for things that succeeded but probably are not what was wanted. */
  warnings: string[];
  /** One entry per language, including the base. */
  languages: LanguageComposition[];
}

interface RegistryEntry {
  id: string;
  videoName: string;
  componentName: string;
  importPath: string;
  durationInFrames: number;
  fps: number;
  width: number;
  height: number;
}

interface BeatLike {
  id: string;
  start: number;
  duration: number;
}

/**
 * Registry of every video this project has stitched, one entry per stitch_composition
 * call, at src/videos/.registry.json. Root.tsx is fully regenerated from this file on
 * every call rather than round-tripped via regex/JSX parsing, which is what makes it
 * safe to never clobber a composition a prior call registered for a different video:
 * the registry (not Root.tsx itself) is the actual source of truth. Deliberately not
 * part of openvidstudio.config.json: that shape is pinned for Task 5 to depend on,
 * this is internal bookkeeping local to this one tool.
 */
function registryPath(projectRoot: string): string {
  return path.join(projectRoot, "src", "videos", ".registry.json");
}

function readRegistry(projectRoot: string): RegistryEntry[] {
  const p = registryPath(projectRoot);
  if (!fs.existsSync(p)) return [];
  return JSON.parse(fs.readFileSync(p, "utf8")) as RegistryEntry[];
}

function writeRegistry(projectRoot: string, entries: RegistryEntry[]): void {
  const p = registryPath(projectRoot);
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, JSON.stringify(entries, null, 2) + "\n", "utf8");
}

function renderRootTsx(entries: RegistryEntry[], hasBrand: boolean): string {
  const imports = entries.map((e) => `import { ${e.componentName} } from "${e.importPath}";`).join("\n");
  // Brand has to evaluate before any scene module, because applyBrand mutates the
  // shared token objects rather than replacing them. Import order is evaluation order.
  const brandImport = hasBrand
    ? '// Brand first. applyBrand mutates the shared tokens, so this has to run\n' +
      '// before any scene module reads them.\nimport "./brand";\n\n'
    : "";
  const comps = entries
    .map(
      (e) =>
        `      <Composition\n        id="${e.id}"\n        component={${e.componentName}}\n` +
        `        durationInFrames={${e.durationInFrames}}\n        fps={${e.fps}}\n` +
        `        width={${e.width}}\n        height={${e.height}}\n      />`,
    )
    .join("\n");
  return `// AUTO-GENERATED by openvidstudio's stitch_composition MCP tool.
// Source of truth is src/videos/.registry.json -- hand edits to this file are lost the
// next time stitch_composition runs for ANY video in this project, not just the one you
// edited. Add a video by calling stitch_composition, not by editing this directly.

${brandImport}import React from "react";
import { Composition } from "remotion";
${imports}

export const RemotionRoot: React.FC = () => {
  return (
    <>
${comps}
    </>
  );
};
`;
}

function renderDemoTsx(opts: {
  componentName: string;
  beats: BeatLike[];
  /** language -> beatId -> public-relative mp3 path. */
  voByLanguage: Record<string, Record<string, string>>;
  baseLanguage: string;
  musicBedFound: boolean;
}): string {
  const { componentName, beats, voByLanguage, baseLanguage, musicBedFound } = opts;
  const sceneImports = beats
    .map((b) => `import { ${pascalCase(b.id)} } from "./scenes/${pascalCase(b.id)}";`)
    .join("\n");
  const sceneMapLines = beats.map((b) => `  ${JSON.stringify(b.id)}: ${pascalCase(b.id)},`).join("\n");

  const voBlocks = Object.entries(voByLanguage)
    .map(([lang, map]) => {
      const lines = Object.entries(map)
        .map(([id, rel]) => `    ${JSON.stringify(id)}: ${JSON.stringify(rel)},`)
        .join("\n");
      return `  ${JSON.stringify(lang)}: {\n${lines}\n  },`;
    })
    .join("\n");

  const musicBedBlock = musicBedFound
    ? `      <Sequence from={0} durationInFrames={DURATION_IN_FRAMES} layout="none">
        <Audio src={staticFile("audio/music-bed.mp3")} volume={0.18} loop />
      </Sequence>
`
    : "";

  // One component per language, all wrapping the same inner one. The picture is identical
  // across languages, so duplicating the scene tree per language would be a second copy of
  // the thing most likely to be edited.
  const languageComponents = Object.keys(voByLanguage)
    .map((lang) =>
      lang === baseLanguage
        ? `export const ${componentName}: React.FC = () => <Narrated language=${JSON.stringify(lang)} />;`
        : `export const ${componentName}${pascalCase(lang)}: React.FC = () => <Narrated language=${JSON.stringify(lang)} />;`,
    )
    .join("\n");

  return `// AUTO-GENERATED by openvidstudio's stitch_composition MCP tool from beats.json.
// Re-run stitch_composition after editing beats.json rather than hand-editing this file;
// it will be overwritten.

import React from "react";
import { AbsoluteFill, Audio, Sequence, Series, staticFile } from "remotion";
import beats from "./beats.json";
${sceneImports}

const SCENES: Record<string, React.FC> = {
${sceneMapLines}
};

// Only the narration differs per language, so there is one scene tree and one audio map
// per language over it.
const VO_FILES: Record<string, Record<string, string>> = {
${voBlocks}
};

const last = beats.beats[beats.beats.length - 1];
export const DURATION_IN_FRAMES = last.start + last.duration;

const Narrated: React.FC<{ language: string }> = ({ language }) => {
  const vo = VO_FILES[language] ?? {};
  return (
    <AbsoluteFill>
      <Series>
        {beats.beats.map((b) => {
          const Scene = SCENES[b.id];
          return (
            <Series.Sequence key={b.id} durationInFrames={b.duration} name={b.id}>
              <Scene />
            </Series.Sequence>
          );
        })}
      </Series>
      {beats.beats
        .filter((b) => vo[b.id])
        .map((b) => (
          <Sequence key={\`vo-\${b.id}\`} from={b.start} durationInFrames={b.duration} layout="none">
            <Audio src={staticFile(vo[b.id])} volume={0.9} />
          </Sequence>
        ))}
${musicBedBlock}    </AbsoluteFill>
  );
};

${languageComponents}
`;
}

/**
 * Reads src/videos/<videoName>/beats.json and writes the composition + updates
 * src/Root.tsx (via the registry above). VO convention: public/audio/vo/<beatId>.mp3,
 * included only if the file actually exists on disk (mirrors PepirosDemo.tsx, where
 * the cta beat has no VO entry because none was recorded). Music bed convention:
 * public/audio/music-bed.mp3, included as a full-duration looping layer only if it
 * exists.
 */
const LANGUAGE_TAG = /^[A-Za-z]{2,8}(-[A-Za-z0-9]{2,8})*$/;

function sanitizeLanguage(tag: string): string {
  if (!LANGUAGE_TAG.test(tag)) {
    throw new Error(`"${tag}" is not a BCP-47 language tag, and it is used as a directory name.`);
  }
  return tag;
}

export function runStitchComposition(input: StitchCompositionInput): StitchCompositionResult {
  const videoName = sanitizeSegment(input.videoName, "videoName");
  const projectRoot = resolveProjectRoot(input.projectRoot);
  const videoDir = path.join(projectRoot, "src", "videos", videoName);
  const beatsPath = path.join(videoDir, "beats.json");

  if (!fs.existsSync(beatsPath)) {
    throw new Error(`${beatsPath} does not exist. Call write_beats_file for "${videoName}" first.`);
  }
  const beatsData = JSON.parse(fs.readFileSync(beatsPath, "utf8")) as {
    fps?: number;
    beats?: BeatLike[];
  };
  const beats = beatsData.beats;
  if (!Array.isArray(beats) || beats.length === 0) {
    throw new Error(`${beatsPath} has no beats.`);
  }

  const config = loadConfig(projectRoot);
  const fps = beatsData.fps ?? config.videoConfig.fps;
  const last = beats[beats.length - 1];
  const durationInFrames = last.start + last.duration;

  const baseLanguage = sanitizeLanguage(input.baseLanguage ?? "en");
  const languages = (input.languages?.length ? input.languages : [baseLanguage]).map(sanitizeLanguage);
  if (!languages.includes(baseLanguage)) languages.unshift(baseLanguage);

  const voByLanguage: Record<string, Record<string, string>> = {};
  const warnings: string[] = [];
  const languageReports: LanguageComposition[] = [];

  const componentName = `${pascalCase(videoName)}Demo`;

  for (const language of languages) {
    const isBase = language === baseLanguage;
    // The base language keeps the original flat path, so nothing that already has
    // narration has to move.
    const publicRel = isBase ? "audio/vo" : `audio/vo/${language}`;
    const map: Record<string, string> = {};
    for (const b of beats) {
      if (fs.existsSync(path.join(projectRoot, "public", ...publicRel.split("/"), `${b.id}.mp3`))) {
        map[b.id] = `${publicRel}/${b.id}.mp3`;
      }
    }
    voByLanguage[language] = map;

    const missing = beats.map((b) => b.id).filter((id) => !(id in map));
    if (missing.length > 0) {
      const detail =
        `${missing.length} of ${beats.length} beats have no ${language} narration file and will render ` +
        `silent: ${missing.join(", ")}. Expected at public/${publicRel}/<beatId>.mp3. ` +
        `Run generate_narration, or accept the silence deliberately.`;
      // Per language, deliberately: a video that is fully narrated in English and half
      // narrated in Hindi is a failure of the Hindi cut, and saying so once for the whole
      // stitch would hide which cut is broken.
      if (input.requireNarration === true) {
        throw new Error(`Narration is required for this composition but ${detail}`);
      }
      warnings.push(detail);
    }

    languageReports.push({
      language,
      compositionId: isBase ? componentName : `${componentName}${pascalCase(language)}`,
      voBeatsFound: Object.keys(map),
      voBeatsMissing: missing,
    });
  }

  const voMap = voByLanguage[baseLanguage];
  const voBeatsMissing = languageReports.find((r) => r.language === baseLanguage)!.voBeatsMissing;
  const musicBedFound = fs.existsSync(path.join(projectRoot, "public", "audio", "music-bed.mp3"));

  const demoTsx = renderDemoTsx({ componentName, beats, voByLanguage, baseLanguage, musicBedFound });
  const demoPath = path.join(videoDir, `${componentName}.tsx`);
  fs.writeFileSync(demoPath, demoTsx, "utf8");

  const entries = readRegistry(projectRoot).filter((e) => e.videoName !== videoName);
  for (const report of languageReports) {
    entries.push({
      id: report.compositionId,
      videoName,
      componentName: report.compositionId,
      importPath: `./videos/${videoName}/${componentName}`,
      durationInFrames,
      fps,
      width: config.videoConfig.width,
      height: config.videoConfig.height,
    });
  }
  writeRegistry(projectRoot, entries);

  const rootPath = path.join(projectRoot, "src", "Root.tsx");
  fs.writeFileSync(
    rootPath,
    renderRootTsx(entries, fs.existsSync(path.join(projectRoot, "src", "brand.ts"))),
    "utf8",
  );

  return {
    written: true,
    compositionId: componentName,
    demoPath,
    rootPath,
    durationInFrames,
    voBeatsFound: Object.keys(voMap),
    voBeatsMissing,
    musicBedFound,
    warnings,
    languages: languageReports,
  };
}

export function registerStitchComposition(server: McpServer): void {
  server.registerTool(
    "stitch_composition",
    {
      title: "Stitch a video's beats into a composition",
      description:
        "Reads src/videos/<videoName>/beats.json and writes src/videos/<videoName>/<PascalName>Demo.tsx: a " +
        "SCENES map from beat id to its scaffold_scene component (imported from ./scenes/<BeatId>, the same " +
        "PascalCase convention scaffold_scene uses -- beats without a scaffolded scene file will fail to " +
        "type-check, scaffold every beat first), a <Series> of <Series.Sequence> per beat, a VO Audio layer " +
        "per beat only where public/audio/vo/<beatId>.mp3 actually exists on disk, and a looping " +
        "full-duration music bed layer if public/audio/music-bed.mp3 exists. Also (re)registers the " +
        "composition in src/Root.tsx (via an internal src/videos/.registry.json this tool owns), without " +
        "clobbering compositions a prior stitch_composition call registered for a different video in the " +
        "same project. Pass languages to emit one composition per language: the picture is shared and only the "
        + "narration layer differs, so the generated file carries one scene tree and one audio map per "
        + "language, reading public/audio/vo/<lang>/<beatId>.mp3 for every language but the base, which "
        + "keeps the original flat path. requireNarration is then enforced per language, because a video "
        + "fully narrated in English and half narrated in Hindi is a failure of the Hindi cut and saying so "
        + "once for the whole stitch would hide which cut is broken.",
      inputSchema: {
        projectRoot: z.string().optional(),
        videoName: z.string().min(1),
        requireNarration: z.boolean().optional(),
        languages: z.array(z.string()).optional(),
        baseLanguage: z.string().optional(),
      },
    },
    async (input) => runTool("stitch_composition", () => runStitchComposition(input)),
  );
}
